version: '3.8'

services:
  mail-server:
    build: .
    container_name: mail-server-app
    ports:
      - "25:25"      # SMTP port
      - "54321:54321" # API port
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
      - mail_data:/app/data
    restart: unless-stopped
    networks:
      - mail-network

  frontend:
    image: node:18-alpine
    container_name: mail-server-frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"
    command: >
      sh -c "npm install && npm run serve"
    networks:
      - mail-network
    depends_on:
      - mail-server

networks:
  mail-network:
    driver: bridge

volumes:
  mail_data:
    driver: local
